### PR TITLE
Add option for manual freqs in the spi-fitter

### PR DESCRIPTION
**Pull request by Mulan-94**
Hi @landmanbester, I realised that the SPI fitter assumes that frequencies in the model and residual cubes increases monotonically. For my use-case however, I am selecting sub-band images irregularly due to significant differences in PSF sizes. With the current setup, I get an inaccurate SPI map. Therefore, I've added an option for manually providing channel frequencies with this pull request. I tested this with my data and I seem to get the results I expect, hence the pull request

### CODE REVIEW

**Comment by landmanbester** [comment]
Thanks for the PR @Mulan-94. Looks good to me. Let's just make sure the tests pass

**Comment by landmanbester** [comment]
Wait a minute. This is probably a bug in data_from_header. Are the frequencies in the header correct?

**Comment by Mulan-94** [comment]
When the images are stacked by `fitstools` for example,it seems that there is just one reference frequency stored. And then `data_from_header` calculates the rest of the frequencies.

> This is probably a bug in data_from_header

I wouldn't really say it's a bug.

**Comment by landmanbester** [comment]
As far as I know, according to the fits standard, the frequencies should be defined on a regular grid and in ascending order. I guess fitstool can't enforce that if you select a subset of the frequencies to stack. This is not a problem I just don't want users doing this manually when they don't need to. Can you please just add something like "By default these are taken from the fits header. Only specify them here if you have a non-standard fits header." to the docstring of the parameter?

**Comment by landmanbester** [comment]
Awesome, thanks again @Mulan-94

**Comment by Mulan-94** [comment]
No, thank you for this simple tool 😃!

**Pull request merged**
